### ISSUE TITLE
amphp/http-server v3 support

### ISSUE THREAD

**Issue by Nek-** [labrador-kennel/http-cors#34]
This package looks really lovely thank you for building it. 

However, there seems to be no trace of a plan to support the next version of amphp http server (which uses amphp v3). So here is a ticket to keep track of this.

Btw: do you want help on this?

**Comment by cspray** [comment]
Hi! Thank you for submitting this issue.

I plan on fully supporting the next major version of Amp using Fibers. I'm really excited about what Amp v3 brings!

I will _try_ to start looking into this next week. I've already done a fair amount of work with the next version ofamphp/http-server so I expect for it to be straight-forward.

Thanks!

**Comment by cspray** [comment]
Wanted to let you know I started a Discussion on how I plan to get this library to a stable 1.0 release. https://github.com/labrador-kennel/http-cors/discussions/36
