### ISSUE TITLE
Header Comparison is case sensitive

### ISSUE THREAD

**Issue by cspray** [labrador-kennel/http-cors#5]
We are comparing headers in a case sensitive manner which could cause potential errors. We should update the comparison to ensure it is case insensitive.

**Comment by cspray** [comment]
@enumag Was hoping to get some more information on what exactly we're looking for with the case insensitive header comparison. Are we just wanting to do this for the Origin header check or all header checks?

**Comment by enumag** [comment]
origin headers + allowed headers in OPTIONS I think

**Comment by cspray** [comment]
Fixed with #24
