### ISSUE TITLE
Update ArrayConfiguration to allow for reasonable default values

### ISSUE THREAD

**Issue by cspray** [labrador-kennel/http-cors#6]
Currently calling `ArrayConfiguration::getMaxAge()` when a max age has not been set results in a key not found error. We should update the `Configuration::getMaxAge()` to return `?int` and handle the case where the browser's default max age should be used.

---

Additionally the other values should have a reasonable default created for them. If a value is required it should be forced to be provided in the Constructor.

**Comment by enumag** [comment]
> Currently calling ArrayConfiguration::getMaxAge() when a max age has not been set results in a key not found error

The same applies for other keys as well. Those that can should have a reasonable default value, others should be required by the constructor.

**Comment by enumag** [comment]
Actually... more likely not reasonable defaults but allow null which would make the header in question to not be included at all.

**Comment by cspray** [comment]
So from my perspective it seems like this is already taken care of for everything other than the maxAge value and possibly allowed methods. The origin seems like it would be required and nothing can work if it is null. The Allow-Headers and Expose-Headers aren't added if the array is empty. shouldAllowCredentials implicitly controls whether the header is included and shouldn't return null. https://github.com/labrador-kennel/http-cors/blob/master/src/CorsMiddleware.php#L68-L82

Is there a reason why you _wouldn't_ include at least 1 HTTP method in Allow-Methods?

**Comment by enumag** [comment]
No I don't think so. 👍

**Comment by cspray** [comment]
So if you attempt to instantiate an ArrayConfiguration or call ConfigurationBuilder.build() without an origin or at least 1 allowed method we throw an exception? Do you have any feedback on what type? Could go with an `\InvalidArgumentException` or we could introduce a library specific exception that is thrown.

**Comment by enumag** [comment]
`\InvalidArgumentException` is fine I think.
