### ISSUE TITLE
Introduce a new system for building Configuration instances

### ISSUE THREAD

**Issue by cspray** [labrador-kennel/http-cors#7]
The ArrayConfiguration object, while potentially useful (particularly in testing contexts), isn't as user-friendly as we should strive to be. A new Configuration builder module should be created that allows for scalar-type checking and a more developer friendly experience creating configuration.

---

- [x] Do we want to allow loading Configuration instances from the filesystem? (e.g. JSON files)
- [x] Allow Configuration::getOrigin to return an array of strings?

**Comment by cspray** [comment]
@enumag looking at the new builder API and I was wondering if it makes sense for a Configuration to allow multiple Origin URL to be returned instead of just one. What do you think?

**Comment by enumag** [comment]
@cspray I think it does. You might want to allow CORS requests from multiple domains I think.

**Comment by cspray** [comment]
Created #14 to address this, thanks.
