### ISSUE TITLE
Allow for different Configuration instances to be used based on URL path

### ISSUE THREAD

**Issue by cspray** [labrador-kennel/http-cors#8]
Sometimes different CORs settings are required for different portions of an application. It would be useful if the middleware were able to load Configuration instances based on a regex matching of the URL path.

> Please note that it is is possible this feature does not make the 0.3 release.

**Comment by enumag** [comment]
another possibility could be a callback-based configuration (instead of regex based). The callback would receive a domain and path (or maybe simply Request instance?) and return a Configuration object. This could also serve as an alternative to https://github.com/labrador-kennel/http-cors/issues/14.

**Comment by cspray** [comment]
What I was thinking for this feature was something like...

```
use Amp\Http\Server\Request;
use Cspray\Labrador\Http\Cors\Configuration;

interface ConfigurationLoader {

    public function loadConfiguration(Request $request) : Configuration;

}
```

This would allow implementations to do whatever they'd like to determine the appropriate Configuration. I would imagine an initial 0.3 release does not actually implement a regex based matcher but a simple `SingleConfigurationConfigurationLoader` (that name is awful) that takes in a single Configuration object that is always returned. It emulates existing functionality well and I'd rather implement a more complex `ConfigurationLoader` when myself or another user of the library is actually encountering the need for it. I do want to give end users the possibility to create their own implementation though so they don't have to wait on me to implement something more complex themselves.

**Comment by enumag** [comment]
I agree completely. Implementation itself is not important. Having the appropriate API to allow it is.
